<?php 
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category    Conshiy
 * @package     Conshiy_Slave
 * @copyright   Copyright (c) 2014 a356 Development (http://www.a356dev.com)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<script type="text/javascript">
    //<![CDATA[
    function conshiyValidate() {
        new Ajax.Request('<?php echo $this->getAjaxCheckUrl() ?>', {
            method: 'post',
            parameters: {
                url: $('slave_config_master_wsdl').value,
                username: $('slave_config_master_username').value,
                token: $('slave_config_master_password').value
             },
            requestHeaders: {Accept: 'application/json'},
            onSuccess: function(transport){
	            if (transport.responseText){
	            	result = transport.responseText.evalJSON();
	                alert( result.message );
	            }
            }
        });
    }
    //]]>
</script>
<?php echo $this->getButtonHtml() ?>